import * as React from "react"
import { Building2, ChevronDown, ChevronRight, Pencil, Plus, Trash2, UserRound } from "lucide-react"
import { Link } from "react-router-dom"
import { toast } from "sonner"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { createDepartment, deleteDepartment, fetchAgentTemplates, fetchDepartments, updateDepartment } from "@/lib/api"
import { useAppState } from "@/lib/state"
import type { AgentTemplate, Department } from "@/types"

export function DepartmentsPage() {
  const { state, refresh } = useAppState()
  const [departments, setDepartments] = React.useState<Department[]>([])
  const [templates, setTemplates] = React.useState<AgentTemplate[]>([])
  const [editing, setEditing] = React.useState<Department | null>(null)
  const [expanded, setExpanded] = React.useState<Set<string>>(new Set())
  const [name, setName] = React.useState(""); const [code, setCode] = React.useState(""); const [description, setDescription] = React.useState(""); const [leader, setLeader] = React.useState(""); const [parent, setParent] = React.useState("")
  const agents = state?.agents ?? []
  const load = React.useCallback(() => { void fetchDepartments().then((items) => { setDepartments(items); setExpanded((current) => current.size ? current : new Set(items.filter((item) => !item.parentId).map((item) => item.id))) }).catch((e) => toast.error(e instanceof Error ? e.message : "读取组织架构失败")) }, [])
  React.useEffect(() => { load() }, [load])
  React.useEffect(() => { void fetchAgentTemplates().then(setTemplates).catch(() => undefined) }, [])
  const open = (item?: Department) => { setEditing(item ?? null); setName(item?.name ?? ""); setCode(item?.code ?? ""); setDescription(item?.description ?? ""); setLeader(item?.leaderAgentId ?? ""); setParent(item?.parentId ?? "") }
  const save = async () => { if (!name.trim() || !code.trim()) { toast.error("部门名称和编码不能为空"); return }; try { const input = { name, code, description, leaderAgentId: leader, enabled: true, parentId: parent }; if (editing) await updateDepartment(editing.id, input); else await createDepartment(input); toast.success("部门已保存"); open(); load(); await refresh() } catch (e) { toast.error(e instanceof Error ? e.message : "保存部门失败") } }
  const remove = async (id: string) => { try { await deleteDepartment(id); toast.success("部门已删除"); load(); await refresh() } catch (e) { toast.error(e instanceof Error ? e.message : "删除部门失败") } }
  const childrenOf = (parentId: string) => departments.filter((item) => (item.parentId || "") === parentId)
  const depth = (item: Department) => { let level = 0; let current = item.parentId; const seen = new Set<string>(); while (current && !seen.has(current)) { seen.add(current); level++; current = departments.find((candidate) => candidate.id === current)?.parentId ?? "" }; return Math.min(level, 6) }
  const renderDepartment = (department: Department): React.ReactNode => { const members = agents.filter((agent) => agent.departmentId === department.id); const leaderAgent = agents.find((agent) => agent.id === department.leaderAgentId); const children = childrenOf(department.id); const isExpanded = expanded.has(department.id); return <React.Fragment key={department.id}><div className="rounded-xl border bg-card p-4" style={{ marginLeft: `${depth(department) * 18}px` }}><div className="flex items-start gap-3"><Button size="icon" variant="ghost" className="mt-[-4px]" onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(department.id)) next.delete(department.id); else next.add(department.id); return next })}>{isExpanded ? <ChevronDown /> : <ChevronRight />}</Button><Building2 className="mt-1 size-5 text-primary"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{department.name}</span><code className="text-xs text-muted-foreground">{department.code}</code><Badge variant={department.enabled ? "secondary" : "outline"}>{department.enabled ? "启用" : "停用"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{department.description || "暂无部门说明"}</p><p className="mt-2 text-xs text-muted-foreground">负责人：{leaderAgent?.name ?? "未设置"} · 员工：{members.length} 人 · 下级部门：{children.length} 个</p></div><Button size="icon" variant="ghost" onClick={() => open(department)}><Pencil /></Button><Button size="icon" variant="ghost" onClick={() => void remove(department.id)}><Trash2 /></Button></div>{isExpanded && members.length > 0 ? <div className="mt-3 space-y-2 border-t pt-3">{members.map((agent) => { const template = templates.find((item) => item.id === agent.templateId); const chineseName = template?.metadata.chineseName || agent.name; const englishName = template?.metadata.englishName || agent.id; return <Link key={agent.id} to={`/agents?agent=${encodeURIComponent(agent.id)}`} className="flex items-center gap-3 rounded-lg px-3 py-2 hover:bg-muted"><UserRound className="size-4 text-muted-foreground"/><span className="min-w-0 flex-1"><span className="block truncate text-sm">{chineseName}</span><span className="block truncate text-xs text-muted-foreground">{englishName}</span></span><span className="text-xs text-muted-foreground">{agent.description || agent.category}</span><Badge variant={agent.enabled ? "secondary" : "outline"}>{agent.enabled ? "在职" : "停用"}</Badge></Link> })}</div> : null}</div>{isExpanded ? children.map(renderDepartment) : null}</React.Fragment> }
  return <div className="flex flex-col gap-6"><PageHeader eyebrow="Organization" title="组织架构" description="统一管理部门层级、部门负责人和员工。展开部门即可查看员工信息，点击员工可编辑完整配置。" actions={<Button onClick={() => open()}><Plus data-icon="inline-start" />新增部门</Button>} /><div className="grid gap-4 lg:grid-cols-[1fr_360px]"><Card><CardHeader><CardTitle>部门与员工</CardTitle></CardHeader><CardContent className="space-y-2">{departments.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">还没有部门</p> : childrenOf("").map(renderDepartment)}{agents.some((agent) => !agent.internal && !agent.departmentId) ? <div className="rounded-xl border border-dashed p-4"><p className="text-sm font-medium">待归属员工</p>{agents.filter((agent) => !agent.internal && !agent.departmentId).map((agent) => <Link key={agent.id} to={`/agents?agent=${encodeURIComponent(agent.id)}`} className="mt-2 flex items-center gap-2 text-sm text-primary"><UserRound className="size-4" />{agent.name}</Link>)}</div> : null}</CardContent></Card><Card><CardHeader><CardTitle>{editing ? "编辑部门" : "新建部门"}</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="部门名称" value={name} onChange={(e) => setName(e.target.value)} /><Input placeholder="部门编码" value={code} onChange={(e) => setCode(e.target.value)} /><Textarea placeholder="部门职责和介绍" value={description} onChange={(e) => setDescription(e.target.value)} rows={5} /><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={parent} onChange={(e) => setParent(e.target.value)}><option value="">顶级部门</option>{departments.filter((item) => item.id !== editing?.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={leader} onChange={(e) => setLeader(e.target.value)}><option value="">选择部门负责人</option>{agents.filter((agent) => !agent.internal).map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => open()}>清空</Button><Button onClick={() => void save()}>保存部门</Button></div></CardContent></Card></div></div>
}
