import {ArrowRight,ListTodo,Plus} from "lucide-react"
import {Link} from "react-router-dom"
import {PageHeader} from "@/components/page-header"
import {StatusBadge} from "@/components/status-badge"
import {Button} from "@/components/ui/button"
import {Card,CardContent} from "@/components/ui/card"
import {Empty,EmptyDescription,EmptyHeader,EmptyMedia,EmptyTitle} from "@/components/ui/empty"
import {Progress} from "@/components/ui/progress"
import {formatTime} from "@/lib/format"
import {useAppState} from "@/lib/state"
export function TasksPage(){const{state}=useAppState();const tasks=(state?.issues??[]).filter(i=>!i.parentId);return <div className="flex flex-col gap-7"><PageHeader eyebrow="Workspace" title="任务" description="顶层 Issue 代表用户目标；进度由它的子 Issues 自动汇总。" actions={<Button render={<Link to="/tasks/new"/>}><Plus/>发布任务</Button>}/>{tasks.length===0?<Card><CardContent className="py-16"><Empty><EmptyHeader><EmptyMedia variant="icon"><ListTodo/></EmptyMedia><EmptyTitle>还没有任务</EmptyTitle><EmptyDescription>发布目标后，Pi 会创建真实的执行计划。</EmptyDescription></EmptyHeader></Empty></CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{tasks.map(task=>{const children=state?.issues.filter(i=>i.parentId===task.id)??[];const complete=children.filter(i=>["done","cancelled"].includes(i.status)).length;const progress=children.length?Math.round(complete/children.length*100):task.status==="done"?100:0;const active=state?.executions.filter(e=>e.issueId===task.id||children.some(i=>i.id===e.issueId)).filter(e=>["queued","starting","running","waiting_approval"].includes(e.status)).length??0;return <Card key={task.id} className="group transition-shadow hover:shadow-md"><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-mono text-xs text-muted-foreground">{task.identifier}</span><StatusBadge status={task.status}/></div><h2 className="mt-3 line-clamp-2 font-medium leading-6">{task.title}</h2></div><Button variant="ghost" size="icon-sm" render={<Link to={`/tasks/${task.id}`} aria-label="查看任务"/>}><ArrowRight/></Button></div><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><Stat label="子 Issues" value={children.length}/><Stat label="活跃执行" value={active}/><Stat label="完成度" value={`${progress}%`}/></div><Progress value={progress} className="mt-5 h-1.5"/><p className="mt-4 truncate text-xs text-muted-foreground">{task.workspace} · {formatTime(task.updatedAt)}</p></CardContent></Card>})}</div>}</div>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-lg bg-muted/50 p-3"><p className="text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium tabular-nums">{value}</p></div>}
